// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACCV4RIaLMaOY5AOO6TBytMFld5TQtjMU',
    appId: '1:962230880867:web:c263a478b0b1be27990656',
    messagingSenderId: '962230880867',
    projectId: 'joudmart-366c0',
    authDomain: 'joudmart-366c0.firebaseapp.com',
    storageBucket: 'joudmart-366c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkahdKtkD3gRoGEURtRmQwWtjJkpa3LCw',
    appId: '1:962230880867:android:92c3f578f8e263be990656',
    messagingSenderId: '962230880867',
    projectId: 'joudmart-366c0',
    storageBucket: 'joudmart-366c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbBeeH_rkmNcoQTEV_R8ba4b8HincX8ak',
    appId: '1:962230880867:ios:1eaebe77ec9b18bd990656',
    messagingSenderId: '962230880867',
    projectId: 'joudmart-366c0',
    storageBucket: 'joudmart-366c0.appspot.com',
    iosBundleId: 'com.example.joudmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbBeeH_rkmNcoQTEV_R8ba4b8HincX8ak',
    appId: '1:962230880867:ios:1eaebe77ec9b18bd990656',
    messagingSenderId: '962230880867',
    projectId: 'joudmart-366c0',
    storageBucket: 'joudmart-366c0.appspot.com',
    iosBundleId: 'com.example.joudmart',
  );
}
