import 'package:joudmart/models/product.dart';

final List<List<Product>> sections = [
  [
    Product(
      id: 1,
      name: 'روبوت كوزمو Cozmo Robot by Anki',
      price: 1499,
      discountPrice: 999,
      imageUrl: 'assets/cozmo.png',
    ),
    Product(
      id: 2,
      name: 'روبوت البرمجة المتقدم (Mbotranger) ',
      price: 1600,
      discountPrice: 800,
      imageUrl: 'assets/mbot-ranger.png',
    ),
    Product(
      id: 3,
      name: 'روبوت استروبوت (AstroBot Robot)',
      price: 1499,
      discountPrice: 999,
      imageUrl: 'assets/astrobot.png',
    ),
    Product(
      id: 4,
      name: 'JimuRobot Kit 357 pieces',
      price: 999,
      discountPrice: 699,
      imageUrl: 'assets/jimubot.png',
    ),
    Product(
      id: 5,
      name: 'روبوت كوزمو نسخة كوليكتور Cozmo collector Robot by Anki ',
      price: 1599,
      discountPrice: 1149,
      imageUrl: 'assets/cozmo-collector.png',
    ),
    Product(
      id: 6,
      name: 'روبوت ماكس ميكانو التفاعلي مع الذكاء الاصطناعي ',
      price: 1499,
      discountPrice: 999,
      imageUrl: 'assets/max-meccano.png',
    ),
    Product(
      id: 7,
      name:
          'روبوت بازبوت و ماتبوت UBTECH JIMU Robot BuzzBot & MuttBot 264 قطعة',
      price: 999,
      discountPrice: 699,
      imageUrl: 'assets/buzzbot.png',
    ),
    Product(
      id: 8,
      name: 'حقيبة لحماية روبوت كوزمو Cozmo robot bag',
      price: 400,
      discountPrice: 250,
      imageUrl: 'assets/cozmo-bag.png',
    ),
  ],

//زيوت الشعر

  [
    Product(
      id: 9,
      name: 'زيت الحشيش الأخضر 120 مل',
      price: 36.00,
      discountPrice: 25.00,
      imageUrl: 'assets/green grass 120ml.png',
    ),
    Product(
      id: 10,
      name: 'زيت الأرغان المغربي الأصلي للشعر',
      price: 45.00,
      discountPrice: 25.00,
      imageUrl: 'assets/aragan oil.png',
    ),
    Product(
      id: 11,
      name: 'زيت الحشيش الأخضر 250 مل',
      price: 50.00,
      discountPrice: 35.00,
      imageUrl: 'assets/green-grass.png',
    ),
    Product(
      id: 12,
      name: 'زيت الحية الأصلي 120 مل',
      price: 40.00,
      discountPrice: 25.00,
      imageUrl: 'assets/zayt-hayya (1).png',
    ),
    Product(
      id: 13,
      name: 'زيت الحية الأصلي ٢٥٠ مل',
      price: 55.00,
      discountPrice: 35.00,
      imageUrl: 'assets/zayt-hayee.png',
    ),
    Product(
      id: 14,
      name: 'زيت الحية الممتاز للشعر',
      price: 35.00,
      discountPrice: 20.00,
      imageUrl: 'assets/super-snake-hair.png',
    ),
    Product(
      id: 15,
      name: 'زيت شعر كوبرا',
      price: 45.00,
      discountPrice: 25.00,
      imageUrl: 'assets/cobra oil.png',
    ),
    Product(
      id: 16,
      name: 'زيت شعر بالحبة السوداء 200ml',
      price: 25.00,
      discountPrice: 14.00,
      imageUrl: 'assets/black-seed-oil.png',
    ),
    Product(
      id: 17,
      name: 'زيت شعر بجوز الهند 200ml',
      price: 25.00,
      discountPrice: 14.00,
      imageUrl: 'assets/ginger oil.png',
    )
  ],

  //العسل

  [
    Product(
      id: 17,
      name: 'عسل مع الزنجبيل 250 جرام',
      price: 25.00,
      discountPrice: 19.00,
      imageUrl: 'assets/saffi bilzangabeel.png',
    ),
    Product(
      id: 18,
      name: 'عسل صافي 250 جرام',
      price: 25.00,
      discountPrice: 19.00,
      imageUrl: 'assets/assal-saffi-2.png',
    ),
    Product(
      id: 19,
      name: 'عسل مع الجينسينغ 250 جرام',
      price: 25.00,
      discountPrice: 19.00,
      imageUrl: 'assets/assal-maa-algising.png',
    ),
    Product(
      id: 20,
      name: 'عسل بالحبة السوداء 250 جرام',
      price: 25.00,
      discountPrice: 19.00,
      imageUrl: 'assets/with habba-albaraka.png',
    ),
    Product(
      id: 21,
      name: 'عسل سدر صافي 450 جرام',
      price: 65.00,
      discountPrice: 50.00,
      imageUrl: 'assets/assal-sidr-saffi.png',
    ),
    Product(
      id: 22,
      name: 'عسل بالحبة السوداء 450 جرام',
      price: 70.00,
      discountPrice: 55.00,
      imageUrl: 'assets/assal-belhabba-alsawdaa.png',
    ),
    Product(
      id: 23,
      name: 'عسل مع غذاء الملكات 310 جرام',
      price: 60.00,
      discountPrice: 39.00,
      imageUrl: 'assets/min-ghidda-almalikat.png',
    ),
    Product(
      id: 25,
      name: 'عسل صافي مع حبة البركة 125 جرام',
      price: 18.00,
      discountPrice: 10.00,
      imageUrl: 'assets/saffi-maa-habbatalbaraka.png',
    ),
    Product(
      id: 26,
      name: 'عسل صافي 125 جرام',
      price: 18.00,
      discountPrice: 10.00,
      imageUrl: 'assets/assal-saffi-125g.png',
    ),
    Product(
      id: 27,
      name: 'عسل صافي مع زنجبيل 125 جرام',
      price: 18.00,
      discountPrice: 10.00,
      imageUrl: 'assets/saffi-maa-zangabeel.png',
    ),
    Product(
      id: 28,
      name: 'عسل بالحبة السوداء 610 جرام',
      price: 85.00,
      discountPrice: 65.00,
      imageUrl: 'assets/assal-balhabba-alsawda.png',
    ),
    Product(
      id: 29,
      name: 'عسل سدر صافي 610 جرام ',
      price: 80.00,
      discountPrice: 60.00,
      imageUrl: 'assets/sidr-safi.png',
    ),
    Product(
      id: 30,
      name: 'عسل بالحبة السوداء 340 جرام',
      price: 65.00,
      discountPrice: 45.00,
      imageUrl: 'assets/assal-balhaba-alsawda.png',
    ),
    Product(
      id: 31,
      name: 'عسل صافي بالجينسينغ 125 جرام',
      price: 18.00,
      discountPrice: 10.00,
      imageUrl: 'assets/saffi-billginising.png',
    ),
    Product(
      id: 32,
      name: 'عسل تنحيف 310 جرام',
      price: 75.00,
      discountPrice: 50.00,
      imageUrl: 'assets/assal-tanheef.png',
    ),
    Product(
      id: 33,
      name: 'عسل صافي 1 كلغ',
      price: 130.00,
      discountPrice: 95.00,
      imageUrl: 'assets/assal-saffi-1kg.png',
    ),
    Product(
      id: 34,
      name: 'عسل صافي 600 جرام',
      price: 90.00,
      discountPrice: 60.00,
      imageUrl: 'assets/assal-saffi.png',
    ),
    Product(
      id: 35,
      name: 'مجموعة العسل الخاصة – خلطة عسل 4 في 1',
      price: 55.00,
      discountPrice: 35.00,
      imageUrl: 'assets/speacial honey pack.png',
    ),
  ],

  //الشاي

  [
    Product(
      id: 36,
      name: 'الشاي الأخضر بالورد 20 ظرف',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/green with rose.png',
    ),
    Product(
      id: 37,
      name: 'الشاي الأخضر بالنعناع و الليمون 20 ظرف',
      price: 55.00,
      discountPrice: 35.00,
      imageUrl: 'assets/green-mint-lemon.png',
    ),
    Product(
      id: 38,
      name: 'الشاي الاخضر بالنعناع و الزنجبيل 20 ظرف',
      price: 20.00,
      discountPrice: 13.00,
      imageUrl: 'assets/mint-genger-green.png',
    ),
    Product(
      id: 39,
      name: 'الشاي الأخضر بالنعناع 20 ظرف',
      price: 20.00,
      discountPrice: 13.00,
      imageUrl: 'assets/mint-green.png',
    ),
    Product(
      id: 40,
      name: 'الشاي الأخضر بالليمون20 ظرف',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/green-lemon.png',
    ),
    Product(
      id: 41,
      name: ' الشاي الأخضر بالقرفة 20 ظرف',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/green-cinamon.png',
    ),
    Product(
      id: 42,
      name: 'الشاي الأخضر بالعسل 20 ظرف',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/green-honey.png',
    ),
    Product(
      id: 43,
      name: 'الشاي الأخضر بالزنجبيل20 ظرف ',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/green-ginger.png',
    ),
    Product(
      id: 44,
      name: 'الشاي الأخضر النقية 20 ظرف ',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/pure green.png',
    ),
    Product(
      id: 45,
      name: 'الشاي الأخضر بالبابونج 20 ظرف ',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/green-babonig.png',
    ),
    Product(
      id: 46,
      name: 'شاي التنحيف و الذكاء بمزيج النعناع 20 ظرف',
      price: 25.00,
      discountPrice: 17.00,
      imageUrl: 'assets/with mint.png',
    ),
    Product(
      id: 47,
      name: 'شاي التنحيف و الذكاء بمزيج الفواكه 20 ظرف',
      price: 25.00,
      discountPrice: 17.00,
      imageUrl: 'assets/tea for whight losing with fruit mix.png',
    ),
    Product(
      id: 48,
      name: 'شاي التنحيف و الذكاء بالعسل 20 ظرف',
      price: 25.00,
      discountPrice: 17.00,
      imageUrl: 'assets/tea for whight losing with honey.png',
    ),
    Product(
      id: 49,
      name: 'شاي التنحيف و الذكاء بالتفاح الأخضر 20 ظرف',
      price: 25.00,
      discountPrice: 17.00,
      imageUrl: 'assets/tea for whight losing with green apple.png',
    ),
    Product(
      id: 50,
      name: ' شاي التنحيف لتحسين الوزن',
      price: 23.00,
      discountPrice: 15.00,
      imageUrl: 'assets/whight losing tea.png',
    ),
    Product(
      id: 51,
      name: 'الشاي الأخضر باليانسون 20 ظرف',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/yanson-green-tea.png',
    ),
    Product(
      id: 52,
      name: 'الشاي الأخضر بالهيل 20 ظرف',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/Green-Tea-Cardamom.png',
    ),
    Product(
      id: 53,
      name: 'الشاي الأخضر بالجيسينغ 20 ظرف',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/ginsing tea.png',
    ),
    Product(
      id: 54,
      name: 'الشاي الأخضر بالياسمين 20 ظرف',
      price: 21.00,
      discountPrice: 13.00,
      imageUrl: 'assets/green-yasmeen.png',
    ),
    Product(
      id: 55,
      name: 'الشاي العشبية الخام معجزة الحبة السوداء ',
      price: 28.00,
      discountPrice: 15.00,
      imageUrl: 'assets/miraculous-blackseed.png',
    ),
    Product(
      id: 56,
      name: 'الشاي العشبية الخام معجزة بنكهة الياسمين',
      price: 28.00,
      discountPrice: 15.00,
      imageUrl: 'assets/aromatic-jasmine.png',
    ),
    Product(
      id: 57,
      name: 'الشاي العشبية الخام بنكهة النعناع المنعش والورد',
      price: 28.00,
      discountPrice: 15.00,
      imageUrl: 'assets/refreshing-peppermint-rose-tea.png',
    ),
    Product(
      id: 58,
      name: 'الشاي العشبية الخام بنكهة الكركديه الرائعة',
      price: 28.00,
      discountPrice: 15.00,
      imageUrl: 'assets/exciting-hibiscus-karkadih.png',
    ),
    Product(
      id: 59,
      name: 'الشاي العشبية الخام بنكهة البابونج المهدئ',
      price: 28.00,
      discountPrice: 15.00,
      imageUrl: 'assets/soothing-chamomile-babonig.png',
    ),
    Product(
      id: 60,
      name: 'بيرفيكت دايت شاي الحمية المتكاملة',
      price: 165.00,
      discountPrice: 125.00,
      imageUrl: 'assets/Natural-Perfect-Diet-Tea-2.png',
    ),
  ],

  //كريمات عبق المشرق الفاخرة

  [
    Product(
      id: 61,
      name: 'كريم الورد الفاخر',
      price: 25.00,
      discountPrice: 15.00,
      imageUrl: 'assets/rose-cream.png',
    ),
    Product(
      id: 62,
      name: 'كريم العود الفاخر',
      price: 25.00,
      discountPrice: 15.00,
      imageUrl: 'assets/oud-cream.png',
    ),
    Product(
      id: 63,
      name: 'كريم المسك الفاخر',
      price: 25.00,
      discountPrice: 15.00,
      imageUrl: 'assets/misk-cream.png',
    ),
    Product(
      id: 64,
      name: 'كريم المخلط الفاخر',
      price: 25.00,
      discountPrice: 15.00,
      imageUrl: 'assets/makhalat-cream.png',
    ),
    Product(
      id: 65,
      name: 'كريم العنبر الفاخر',
      price: 25.00,
      discountPrice: 15.00,
      imageUrl: 'assets/amber-cream.png',
    ),
    Product(
      id: 66,
      name: 'كريم البخور الفاخر',
      price: 25.00,
      discountPrice: 15.00,
      imageUrl: 'assets/bakhoor-cream.png',
    ),
  ],

  //الأحجار الجامدة

  [
    Product(
      id: 67,
      name: 'حجر مسك العود المعطر',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/misk_oudh.png',
    ),
    Product(
      id: 68,
      name: 'حجر عنبر جامد معطر',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/ambar_jamid.png',
    ),
    Product(
      id: 69,
      name: 'حجر مسك العربية المعطر',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/misk_arabia.png',
    ),
    Product(
      id: 70,
      name: 'حجر جنات الفردوس المعطر',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/jannat alfirdaws.png',
    ),
    Product(
      id: 71,
      name: 'حجر المسك الجامد',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/misk_jamid.png',
    ),
  ],

//زيوت الطبيعة

  [
    Product(
      id: 72,
      name: 'زيت الخس 250 مل ',
      price: 45.00,
      discountPrice: 30.00,
      imageUrl: 'assets/lucttuce oil.png',
    ),
    Product(
      id: 73,
      name: 'زيت اللوز الحلو 250 مل',
      price: 40.00,
      discountPrice: 28.00,
      imageUrl: 'assets/seet almond oil.png',
    ),
    Product(
      id: 74,
      name: 'زيت الحلبة 250 مل',
      price: 45.00,
      discountPrice: 30.00,
      imageUrl: 'assets/alhilba-oil.png',
    ),
    Product(
      id: 75,
      name: 'زيت الزنجبيل 250 مل',
      price: 45.00,
      discountPrice: 30.00,
      imageUrl: 'assets/ginger-oil.png',
    ),
    Product(
      id: 76,
      name: 'زيت الثوم 250 مل',
      price: 45.00,
      discountPrice: 30.00,
      imageUrl: 'assets/garlic oil .png',
    ),
    Product(
      id: 77,
      name: 'زيت البنفسج 250 مل',
      price: 45.00,
      discountPrice: 30.00,
      imageUrl: 'assets/albanafsaj oil.png',
    ),
    Product(
      id: 78,
      name: 'زيت بذور العنب 250 مل',
      price: 40.00,
      discountPrice: 28.00,
      imageUrl: 'assets/grapes seed oil.png',
    ),
    Product(
      id: 79,
      name: 'زيت بذور الكتان 500 مل',
      price: 65.00,
      discountPrice: 45.00,
      imageUrl: 'assets/linseed oil.png',
    ),
    Product(
      id: 80,
      name: 'زيت القرفة 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/cinamon oil.png',
    ),
    Product(
      id: 81,
      name: 'زيت القراص 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/nettle oil.png',
    ),
    Product(
      id: 82,
      name: 'زيت الخروع 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/castor oil.png',
    ),
    Product(
      id: 83,
      name: 'زيت ذيل الحصان 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/horsetail oil.png',
    ),
    Product(
      id: 84,
      name: 'زيت الخيار 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/cucumber oil.png',
    ),
    Product(
      id: 85,
      name: 'زيت المحلب 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/almahlab oil.png',
    ),
    Product(
      id: 86,
      name: 'زيت الزنجبيل 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/ginger oil 30ml.png',
    ),
    Product(
      id: 87,
      name: 'زيت السمسم 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/simsim oil.png',
    ),
    Product(
      id: 88,
      name: 'زيت المستكة 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/mastic oil.png',
    ),
    Product(
      id: 89,
      name: 'زيت النخالة الأرز 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/rice bran oil.png',
    ),
    Product(
      id: 90,
      name: 'زيت زبدة الشيا 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/shea-butter-oil.png',
    ),
    Product(
      id: 91,
      name: 'زيت الكركديه 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/hibiscus oil.png',
    ),
    Product(
      id: 92,
      name: 'زيت الفانيلا 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/vanilla oil.png',
    ),
    Product(
      id: 93,
      name: 'زيت الخزامى 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/lavandar oil.png',
    ),
    Product(
      id: 94,
      name: 'زيت الحنة 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/henna oil.png',
    ),
    Product(
      id: 95,
      name: 'زيت الخس 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/luttece-oil.png',
    ),
    Product(
      id: 96,
      name: 'زيت البابونج الأزرق 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/blue chamomile oil.png',
    ),
    Product(
      id: 97,
      name: 'زيت الحرمل 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/harmal oil.png',
    ),
    Product(
      id: 98,
      name: 'زيت النانخة 30 مل',
      price: 15.00,
      discountPrice: 9.00,
      imageUrl: 'assets/ajwain oil.png',
    ),
  ],

//مقشرات الوجه

  [
    Product(
      id: 99,
      name: 'غسول الوجه مرطب مع خلاصة الزيتون',
      price: 50.00,
      discountPrice: 18.00,
      imageUrl: 'assets/facewash olive.png',
    ),
    Product(
      id: 100,
      name: 'غسول الوجه بخلاصة النيم لحب الشباب',
      price: 50.00,
      discountPrice: 18.00,
      imageUrl: 'assets/facewash nim.png',
    ),
    Product(
      id: 101,
      name: 'غسول الوجه بخلاصة الليمون للتحكم بالدهون',
      price: 50.00,
      discountPrice: 18.00,
      imageUrl: 'assets/facewash lemon.png',
    ),
    Product(
      id: 102,
      name: 'غسول الوجه بخلاصة الطين للتنظيف العميق',
      price: 50.00,
      discountPrice: 18.00,
      imageUrl: 'assets/facewash mud.png',
    ),
    Product(
      id: 103,
      name: 'غسول الوجه بخلاصة الصبار لبشرة نشيطة',
      price: 50.00,
      discountPrice: 18.00,
      imageUrl: 'assets/facewash cactus.png',
    ),
    Product(
      id: 104,
      name: 'غسول الوجه بخلاصة الخيار لتبييض الوجه',
      price: 50.00,
      discountPrice: 18.00,
      imageUrl: 'assets/facewash cucumber.png',
    ),
    Product(
      id: 105,
      name: 'غسول الوجه بخلاصة الحليب و العسل لتنظيف البشرة',
      price: 50.00,
      discountPrice: 18.00,
      imageUrl: 'assets/facewash milk honey.png',
    ),
    Product(
      id: 106,
      name: 'غسول الوجه بحبة البركة فلورز خلاصة عشبية',
      price: 50.00,
      discountPrice: 22.00,
      imageUrl: 'assets/facewash blackseed.png',
    ),
    Product(
      id: 107,
      name: 'غسول الوجه المتطور بالحبة السوداء',
      price: 50.00,
      discountPrice: 18.00,
      imageUrl: 'assets/facewash pro.png',
    ),
  ],

// مقشرات الوجه

  [
    Product(
      id: 108,
      name: 'مقشر الوجه بخلاصة المشمش و الجوز',
      price: 50.00,
      discountPrice: 20.00,
      imageUrl: 'assets/facescrub appricot.png',
    ),
    Product(
      id: 109,
      name: 'مقشر الوجه بخلاصة اللوز',
      price: 50.00,
      discountPrice: 25.00,
      imageUrl: 'assets/facescrub almond.png',
    ),
    Product(
      id: 110,
      name: 'مقشر الوجه بخلاصة الفواكه السلسة',
      price: 50.00,
      discountPrice: 20.00,
      imageUrl: 'assets/facescrub smooth fruit.png',
    ),
    Product(
      id: 111,
      name: 'مقشر الوجه بخلاصة الرمان و الصبار',
      price: 40.00,
      discountPrice: 20.00,
      imageUrl: 'assets/facescrub cactus.png',
    ),
    Product(
      id: 112,
      name: 'مقشر الوجه بخلاصة الأعشاب 5 ب1',
      price: 40.00,
      discountPrice: 20.00,
      imageUrl: 'assets/facescrub herbs.png',
    ),
    Product(
      id: 113,
      name: 'مقشر الوجه بالحبة السوداء',
      price: 50.00,
      discountPrice: 25.00,
      imageUrl: 'assets/facescrub blackseed.png',
    ),
    Product(
      id: 114,
      name: 'مقشر الوجه بالأرغان',
      price: 50.00,
      discountPrice: 22.00,
      imageUrl: 'assets/facescrub aragan.png',
    ),
    Product(
      id: 115,
      name: 'مقشر الوجه بخلاصة المكاديميا',
      price: 40.00,
      discountPrice: 22.00,
      imageUrl: 'assets/facescrub macadamia.png',
    ),
  ],

//البخور و العود

  [
    Product(
      id: 116,
      name: 'عود ضيوف المجالس المعطر',
      price: 35.00,
      discountPrice: 25.00,
      imageUrl: 'assets/almajlis oud.png',
    ),
    Product(
      id: 117,
      name: 'عود بنت القمر المعطر',
      price: 35.00,
      discountPrice: 25.00,
      imageUrl: 'assets/bint alqamar.png',
    ),
    Product(
      id: 118,
      name: 'عود بنت الشرق المعطر',
      price: 35.00,
      discountPrice: 25.00,
      imageUrl: 'assets/bint alsharq.png',
    ),
    Product(
      id: 119,
      name: 'عود الوجاهة المعطر',
      price: 35.00,
      discountPrice: 25.00,
      imageUrl: 'assets/alwajahaa oud.png',
    ),
    Product(
      id: 120,
      name: 'عود الميثم المعطر',
      price: 35.00,
      discountPrice: 25.00,
      imageUrl: 'assets/almatheem oud.png',
    ),
    Product(
      id: 121,
      name: 'عود الفواح المعطر',
      price: 35.00,
      discountPrice: 25.00,
      imageUrl: 'assets/alfawwah oud.png',
    ),
    Product(
      id: 122,
      name: 'عود الأصيلة المعطر',
      price: 35.00,
      discountPrice: 25.00,
      imageUrl: 'assets/alaseela oud.png',
    ),
    Product(
      id: 123,
      name: 'عود الأُبّهة المعطر',
      price: 35.00,
      discountPrice: 25.00,
      imageUrl: 'assets/alabbaha oud.png',
    ),
    Product(
      id: 124,
      name: 'عود اهلاً و سهلاً المعطر',
      price: 35.00,
      discountPrice: 25.00,
      imageUrl: 'assets/ahlan oud.png',
    ),
    Product(
      id: 125,
      name: 'عود أميرة الشرق المعطر',
      price: 35.00,
      discountPrice: 25.00,
      imageUrl: 'assets/amirat alsharq.png',
    ),
    Product(
      id: 126,
      name: 'دخون هنادي',
      price: 18.00,
      discountPrice: 12.00,
      imageUrl: 'assets/hanadi bakhoor.png',
    ),
    Product(
      id: 127,
      name: 'دخون هلا',
      price: 18.00,
      discountPrice: 12.00,
      imageUrl: 'assets/hala bakhoor.png',
    ),
    Product(
      id: 128,
      name: 'دخون دانة الدنيا',
      price: 18.00,
      discountPrice: 12.00,
      imageUrl: 'assets/dana bakhoor.png',
    ),
    Product(
      id: 129,
      name: 'دخون هنادي',
      price: 18.00,
      discountPrice: 12.00,
      imageUrl: 'assets/hanadi bakhoor.png',
    ),
    Product(
      id: 130,
      name: 'دخون تميم',
      price: 18.00,
      discountPrice: 12.00,
      imageUrl: 'assets/tameem bakhoor.png',
    ),
    Product(
      id: 131,
      name: 'دخون الملوك',
      price: 18.00,
      discountPrice: 12.00,
      imageUrl: 'assets/kings bakhoor.png',
    ),
    Product(
      id: 132,
      name: 'دخون الإمارات',
      price: 18.00,
      discountPrice: 12.00,
      imageUrl: 'assets/emirates bakhoor.png',
    ),
    Product(
      id: 133,
      name: 'دخون اريج',
      price: 18.00,
      discountPrice: 12.00,
      imageUrl: 'assets/areej bakhoor.png',
    ),
  ],

  [
    Product(
      id: 134,
      name: 'جيف صابون قناع الطين',
      price: 12.00,
      discountPrice: 8.00,
      imageUrl: 'assets/mud soap.png',
    ),
    Product(
      id: 135,
      name: 'جيف صابون شد الوجه',
      price: 12.00,
      discountPrice: 8.00,
      imageUrl: 'assets/face soap.png',
    ),
    Product(
      id: 136,
      name: 'جيف صابون حب الشباب',
      price: 12.00,
      discountPrice: 8.00,
      imageUrl: 'assets/young soap.png',
    ),
    Product(
      id: 137,
      name: 'جيف صابون المزيل المزود بالرمان',
      price: 12.00,
      discountPrice: 8.00,
      imageUrl: 'assets/pome soap.png',
    ),
    Product(
      id: 138,
      name: 'جيف صابون الخيار',
      price: 12.00,
      discountPrice: 8.00,
      imageUrl: 'assets/cucu soap.png',
    ),
    Product(
      id: 139,
      name: 'جيف صابون الحية',
      price: 12.00,
      discountPrice: 8.00,
      imageUrl: 'assets/snake soap.png',
    ),
    Product(
      id: 140,
      name: 'جيف صابون الحليب و العسل',
      price: 12.00,
      discountPrice: 8.00,
      imageUrl: 'assets/milk and honey soap.png',
    ),
    Product(
      id: 141,
      name: 'جيف صابون البركة',
      price: 12.00,
      discountPrice: 8.00,
      imageUrl: 'assets/elbaraka soap.png',
    ),
    Product(
      id: 142,
      name: 'جيف صابون البابايا',
      price: 12.00,
      discountPrice: 8.00,
      imageUrl: 'assets/babaya soap.png',
    ),
    Product(
      id: 143,
      name: 'جيف صابون إزالة علامات الشد',
      price: 12.00,
      discountPrice: 8.00,
      imageUrl: 'assets/stress soap.png',
    ),
    Product(
      id: 144,
      name: ' صابون الخزامى',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/lavender soap.png',
    ),
    Product(
      id: 145,
      name: 'صابون الكركم',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/kurkum soap.png',
    ),
    Product(
      id: 146,
      name: 'صابون الكبريت',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/sulphur soap.png',
    ),
    Product(
      id: 147,
      name: 'صابون الغليسيرين – صابون الكالتوس وشجرة الشاي',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/calt soap.png',
    ),
    Product(
      id: 148,
      name: 'صابون العسل والغليسيرين',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/honey soap.png',
    ),
    Product(
      id: 149,
      name: 'صابون الزعفران',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/saffron soap.png',
    ),
    Product(
      id: 150,
      name: 'صابون العسل والغليسيرين',
      price: 12.00,
      discountPrice: 7.00,
      imageUrl: 'assets/honey soap.png',
    ),
    Product(
      id: 151,
      name: 'صابون الخيار و الصبار ',
      price: 22.00,
      discountPrice: 14.00,
      imageUrl: 'assets/cucu and cactus soap.png',
    ),
    Product(
      id: 152,
      name: 'صابون البابايا مع الحليب',
      price: 22.00,
      discountPrice: 14.00,
      imageUrl: 'assets/babaya and soap.png',
    ),
    Product(
      id: 153,
      name: 'صابون الأرغان',
      price: 22.00,
      discountPrice: 14.00,
      imageUrl: 'assets/aragan soap.png',
    ),
  ],
  [
    Product(
      id: 154,
      name: 'شامبو و بلسم 2 في 1',
      price: 22.00,
      discountPrice: 16.00,
      imageUrl: 'assets/2 in 1 shampoo.png',
    ),
    Product(
      id: 155,
      name: 'شامبو وبلسم2 في 1 (ضد القشرة مليء بالفيتامين)',
      price: 22.00,
      discountPrice: 16.00,
      imageUrl: 'assets/anti-dandruff 2 in 1.png',
    ),
    Product(
      id: 156,
      name: 'شامبو وبلسم 2 في 1 (حجم وقوة مع الكيراتين)',
      price: 22.00,
      discountPrice: 16.00,
      imageUrl: 'assets/stress shampoo 2 in 1.png',
    ),
    Product(
      id: 157,
      name: 'شامبو وبلسم 2 في 1 (تغذية طبيعية من الجذور إلى الأطراف)',
      price: 22.00,
      discountPrice: 16.00,
      imageUrl: 'assets/natural feed 2 in 1 shampoo.png',
    ),
    Product(
      id: 158,
      name: 'شامبو وبلسم 2 في 1 لشعر سلس وحريري بخلاصة زيت الأرغان المغربي',
      price: 22.00,
      discountPrice: 16.00,
      imageUrl: 'assets/smooth shampoo.png',
    ),
    Product(
      id: 159,
      name: 'شامبو مانع تساقط الشعر للحجاب',
      price: 22.00,
      discountPrice: 16.00,
      imageUrl: 'assets/hijab shampoo.png',
    ),
  ],
];