import 'package:joudmart/models/product.dart';

final List<List<Product>>sections = [
   [
     Product(
       id: 1,
       name: 'Cozmo Robot by Anki',
       price: 1499,
       discountPrice: 999,
       imageUrl: 'assets/cozmo.png',
     ),
     Product(
       id: 2,
       name: 'Mbotranger Advanced Programming Robot',
       price: 1600,
       discountPrice: 800,
       imageUrl: 'assets/mbot-ranger.png',
     ),
     Product(
       id: 3,
       name: 'AstroBot Robot',
       price: 1499,
       discountPrice: 999,
       imageUrl: 'assets/astrobot.png',
     ),
     Product(
       id: 4,
       name: 'JimuRobot Kit 357 pieces',
       price: 999,
       discountPrice: 699,
       imageUrl: 'assets/jimubot.png',
     ),
     Product(
       id: 5,
       name: 'Cozmo Collector Robot by Anki',
       price: 1599,
       discountPrice: 1149,
       imageUrl: 'assets/cozmo-collector.png',
     ),
     Product(
       id: 6,
       name: 'Max Meccano interactive robot with artificial intelligence',
       price: 1499,
       discountPrice: 999,
       imageUrl: 'assets/max-meccano.png',
     ),
     Product(
       id: 7,
       name:
           'UBTECH JIMU Robot BuzzBot & MuttBot 264 Pieces',
       price: 999,
       discountPrice: 699,
       imageUrl: 'assets/buzzbot.png',
     ),
     Product(
       id: 8,
       name: 'Cozmo robot bag',
       price: 400,
       discountPrice: 250,
       imageUrl: 'assets/cozmo-bag.png',
     ),
   ],

//Hair oils

   [
     Product(
       id: 9,
       name: 'Green cannabis oil 120 ml',
       price: 36.00,
       discountPrice: 25.00,
       imageUrl: 'assets/green grass 120ml.png',
     ),
     Product(
       id: 10,
       name: 'Original Moroccan argan oil for hair',
       price: 45.00,
       discountPrice: 25.00,
       imageUrl: 'assets/aragan oil.png',
     ),
     Product(
       id: 11,
       name: 'Green cannabis oil 250 ml',
       price: 50.00,
       discountPrice: 35.00,
       imageUrl: 'assets/green-grass.png',
     ),
     Product(
       id: 12,
       name: 'original snake oil 120 ml',
       price: 40.00,
       discountPrice: 25.00,
       imageUrl: 'assets/zayt-hayya (1).png',
     ),
     Product(
       id: 13,
       name: 'Original snake oil 250 ml',
       price: 55.00,
       discountPrice: 35.00,
       imageUrl: 'assets/zayt-hayee.png',
     ),
     Product(
       id: 14,
       name: 'Excellent snake oil for hair',
       price: 35.00,
       discountPrice: 20.00,
       imageUrl: 'assets/super-snake-hair.png',
     ),
     Product(
       id: 15,
       name: 'cobra hair oil',
       price: 45.00,
       discountPrice: 25.00,
       imageUrl: 'assets/cobra oil.png',
     ),
     Product(
       id: 16,
       name: 'Black seed hair oil 200ml',
       price: 25.00,
       discountPrice: 14.00,
       imageUrl: 'assets/black-seed-oil.png',
     ),
     Product(
       id: 17,
       name: 'Coconut hair oil 200ml',
       price: 25.00,
       discountPrice: 14.00,
       imageUrl: 'assets/ginger oil.png',
     )
   ],

   //Honey

   [
     Product(
       id: 17,
       name: 'Honey with ginger 250 grams',
       price: 25.00,
       discountPrice: 19.00,
       imageUrl: 'assets/saffi bilzangabeel.png',
     ),
     Product(
       id: 18,
       name: 'Pure honey 250 grams',
       price: 25.00,
       discountPrice: 19.00,
       imageUrl: 'assets/assal-saffi-2.png',
     ),
     Product(
       id: 19,
       name: 'Honey with ginseng 250 grams',
       price: 25.00,
       discountPrice: 19.00,
       imageUrl: 'assets/assal-maa-algising.png',
     ),
     Product(
       id: 20,
       name: 'Black seed honey 250 grams',
       price: 25.00,
       discountPrice: 19.00,
       imageUrl: 'assets/with habba-albaraka.png',
     ),
     Product(
       id: 21,
       name: 'Pure Sidr honey 450 grams',
       price: 65.00,
       discountPrice: 50.00,
       imageUrl: 'assets/assal-sidr-saffi.png',
     ),
     Product(
       id: 22,
       name: 'Black seed honey 450 grams',
       price: 70.00,
       discountPrice: 55.00,
       imageUrl: 'assets/assal-belhabba-alsawdaa.png',
     ),
     Product(
       id: 23,
       name: 'Honey with royal jelly 310 grams',
       price: 60.00,
       discountPrice: 39.00,
       imageUrl: 'assets/min-ghidda-almalikat.png',
     ),
     Product(
       id: 25,
       name: 'Pure honey with black seed 125 grams',
       price: 18.00,
       discountPrice: 10.00,
       imageUrl: 'assets/saffi-maa-habbatalbaraka.png',
     ),
     Product(
       id: 26,
       name: 'Pure honey 125 grams',
       price: 18.00,
       discountPrice: 10.00,
       imageUrl: 'assets/assal-saffi-125g.png',
     ),
     Product(
       id: 27,
       name: 'Pure honey with ginger 125 grams',
       price: 18.00,
       discountPrice: 10.00,
       imageUrl: 'assets/saffi-maa-zangabeel.png',
     ),
     Product(
       id: 28,
       name: 'Black seed honey 610 grams',
       price: 85.00,
       discountPrice: 65.00,
       imageUrl: 'assets/assal-balhabba-alsawda.png',
     ),
     Product(
       id: 29,
       name: 'Pure Sidr honey 610 grams',price: 80.00,
       discountPrice: 60.00,
       imageUrl: 'assets/sidr-safi.png',
     ),
     Product(
       id: 30,
       name: 'Black seed honey 340 grams',
       price: 65.00,
       discountPrice: 45.00,
       imageUrl: 'assets/assal-balhaba-alsawda.png',
     ),
     Product(
       id: 31,
       name: 'Pure honey with ginseng 125 grams',
       price: 18.00,
       discountPrice: 10.00,
       imageUrl: 'assets/saffi-billginising.png',
     ),
     Product(
       id: 32,
       name: 'Slimming honey 310 grams',
       price: 75.00,
       discountPrice: 50.00,
       imageUrl: 'assets/assal-tanheef.png',
     ),
     Product(
       id: 33,
       name: 'Pure honey 1 kg',
       price: 130.00,
       discountPrice: 95.00,
       imageUrl: 'assets/assal-saffi-1kg.png',
     ),
     Product(
       id: 34,
       name: 'Pure honey 600 grams',
       price: 90.00,
       discountPrice: 60.00,
       imageUrl: 'assets/assal-saffi.png',
     ),
     Product(
       id: 35,
       name: 'Special Honey Collection - 4 in 1 Honey Mix',
       price: 55.00,
       discountPrice: 35.00,
       imageUrl: 'assets/speacial honey pack.png',
     ),
   ],

   //Tea

   [
     Product(
       id: 36,
       name: 'Green tea with roses 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/green with rose.png',
     ),
     Product(
       id: 37,
       name: 'Green tea with mint and lemon 20 sachets',
       price: 55.00,
       discountPrice: 35.00,
       imageUrl: 'assets/green-mint-lemon.png',
     ),
     Product(
       id: 38,
       name: 'Green tea with mint and ginger 20 sachets',
       price: 20.00,
       discountPrice: 13.00,
       imageUrl: 'assets/mint-ginger-green.png',
     ),
     Product(
       id: 39,
       name: 'Green tea with mint 20 sachets',
       price: 20.00,
       discountPrice: 13.00,
       imageUrl: 'assets/mint-green.png',
     ),
     Product(
       id: 40,
       name: 'Green tea with lemon 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/green-lemon.png',
     ),
     Product(
       id: 41,
       name: 'Green tea with cinnamon 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/green-cinamon.png',
     ),
     Product(
       id: 42,
       name: 'Green tea with honey 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/green-honey.png',
     ),
     Product(
       id: 43,
       name: 'Green tea with ginger 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/green-ginger.png',
     ),
     Product(
       id: 44,
       name: 'Pure green tea 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/pure green.png',
     ),
     Product(
       id: 45,
       name: 'Green tea with chamomile 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/green-babonig.png',
     ),
     Product(
       id: 46,
       name: 'Slimming and intelligence tea with mint mixture, 20 sachets',
       price: 25.00,
       discountPrice: 17.00,
       imageUrl: 'assets/with mint.png',
     ),
     Product(
       id: 47,
       name: 'Slimming and intelligence tea with a mixture of fruits, 20 sachets',
       price: 25.00,
       discountPrice: 17.00,
       imageUrl: 'assets/tea for white losing with fruit mix.png',
     ),
     Product(
       id: 48,
       name: 'Slimming and intelligence tea with honey 20 sachets',
       price: 25.00,
       discountPrice: 17.00,
       imageUrl: 'assets/tea for white losing with honey.png',
     ),
     Product(
       id: 49,
       name: 'Slimming and intelligence tea with green apple, 20 sachets',
       price: 25.00,
       discountPrice: 17.00,
       imageUrl: 'assets/tea for white losing with green apple.png',
     ),
     Product(
       id: 50,
       name: 'Slimming tea to improve weight',
       price: 23.00,
       discountPrice: 15.00,
       imageUrl: 'assets/whight losing tea.png',
     ),
     Product(
       id: 51,
       name: 'Green tea with anise 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/yanson-green-tea.png',
     ),
     Product(
       id: 52,
       name: 'Green tea with cardamom 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/Green-Tea-Cardamom.png',
     ),
     Product(
       id: 53,
       name: 'Green tea with ginseng 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/ginsing tea.png',
     ),
     Product(
       id: 54,
       name: 'Green tea with jasmine 20 sachets',
       price: 21.00,
       discountPrice: 13.00,
       imageUrl: 'assets/green-yasmeen.png',
     ),
     Product(
       id: 55,
       name: 'Raw Miracle Black Seed Herbal Tea',
       price: 28.00,
       discountPrice: 15.00,
       imageUrl: 'assets/miraculous-blackseed.png',
     ),
     Product(
       id: 56,
       name: 'Jasmine Flavored Miracle Raw Herbal Tea',
       price: 28.00,
       discountPrice: 15.00,
       imageUrl: 'assets/aromatic-jasmine.png',
     ),
     Product(
       id: 57,
       name: 'Raw herbal tea flavored with refreshing mint and rose',
       price: 28.00,
       discountPrice: 15.00,imageUrl: 'assets/refreshing-peppermint-rose-tea.png',
     ),
     Product(
       id: 58,
       name: 'Raw herbal tea with a wonderful hibiscus flavour',
       price: 28.00,
       discountPrice: 15.00,
       imageUrl: 'assets/exciting-hibiscus-karkadih.png',
     ),
     Product(
       id: 59,
       name: 'soothing chamomile flavored raw herbal tea',
       price: 28.00,
       discountPrice: 15.00,
       imageUrl: 'assets/soothing-chamomile-babonig.png',
     ),
     Product(
       id: 60,
       name: 'Perfect Diet Tea',
       price: 165.00,
       discountPrice: 125.00,
       imageUrl: 'assets/Natural-Perfect-Diet-Tea-2.png',
     ),
   ],

   //Luxury fragrance creams of the Levant

   [
     Product(
       id: 61,
       name: 'Luxury Rose Cream',
       price: 25.00,
       discountPrice: 15.00,
       imageUrl: 'assets/rose-cream.png',
     ),
     Product(
       id: 62,
       name: 'Luxury Oud Cream',
       price: 25.00,
       discountPrice: 15.00,
       imageUrl: 'assets/oud-cream.png',
     ),
     Product(
       id: 63,
       name: 'Luxury musk cream',
       price: 25.00,
       discountPrice: 15.00,
       imageUrl: 'assets/misk-cream.png',
     ),
     Product(
       id: 64,
       name: 'Luxury Mukhallat Cream',
       price: 25.00,
       discountPrice: 15.00,
       imageUrl: 'assets/makhalat-cream.png',
     ),
     Product(
       id: 65,
       name: 'Luxury Amber Cream',
       price: 25.00,
       discountPrice: 15.00,
       imageUrl: 'assets/amber-cream.png',
     ),
     Product(
       id: 66,
       name: 'Luxury incense cream',
       price: 25.00,
       discountPrice: 15.00,
       imageUrl: 'assets/bakhoor-cream.png',
     ),
   ],

   //Inanimate stones

   [
     Product(
       id: 67,
       name: 'Musk Oud Fragrant Stone',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/misk_oudh.png',
     ),
     Product(
       id: 68,
       name: 'solid, fragrant amber stone',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/ambar_jamid.png',
     ),
     Product(
       id: 69,
       name: 'Arabic Musk Fragrant Stone',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/misk_arabia.png',
     ),
     Product(
       id: 70,
       name: 'The fragrant stone of Jannat al-Firdaws',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/jannat alfirdaws.png',
     ),
     Product(
       id: 71,
       name: 'solid musk stone',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/misk_jamid.png',
     ),
   ],

//Nature oils

   [
     Product(
       id: 72,
       name: 'Lettuce oil 250 ml',
       price: 45.00,
       discountPrice: 30.00,
       imageUrl: 'assets/lucttuce oil.png',
     ),
     Product(
       id: 73,
       name: 'Sweet Almond Oil 250 ml',
       price: 40.00,
       discountPrice: 28.00,
       imageUrl: 'assets/see almond oil.png',
     ),
     Product(
       id: 74,
       name: 'Fenugreek oil 250 ml',
       price: 45.00,
       discountPrice: 30.00,
       imageUrl: 'assets/alhilba-oil.png',
     ),
     Product(
       id: 75,
       name: 'Ginger oil 250 ml',
       price: 45.00,
       discountPrice: 30.00,
       imageUrl: 'assets/ginger-oil.png',
     ),
     Product(
       id: 76,
       name: 'Garlic oil 250 ml',
       price: 45.00,
       discountPrice: 30.00,
       imageUrl: 'assets/garlic oil .png',
     ),
     Product(
       id: 77,
       name: 'Violet oil 250 ml',
       price: 45.00,
       discountPrice: 30.00,
       imageUrl: 'assets/albanafsaj oil.png',
     ),
     Product(
       id: 78,
       name: 'Grapesseed oil 250 ml',
       price: 40.00,
       discountPrice: 28.00,
       imageUrl: 'assets/grapes seed oil.png',
     ),
     Product(
       id: 79,
       name: 'Flaxseed oil 500 ml',
       price: 65.00,
       discountPrice: 45.00,
       imageUrl: 'assets/linseed oil.png',
     ),
     Product(
       id: 80,
       name: 'Cinnamon oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/cinamon oil.png',
     ),
     Product(
       id: 81,
       name: 'Nettle oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/nettle oil.png',
     ),
     Product(
       id: 82,
       name: 'Castor oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/castor oil.png',
     ),
     Product(
       id: 83,
       name: 'Horsetail oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/horsetail oil.png',
     ),
     Product(
       id: 84,
       name: 'Cucumber oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/cucumber oil.png',
     ),
     Product(
       id: 85,
       name: 'Mahaleb oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/almahlab oil.png',
     ),
     Product(
       id: 86,
       name: 'Ginger oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/ginger oil 30ml.png',
     ),
     Product(
       id: 87,
       name: 'Sesame oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/simsim oil.png',
     ),
     Product(
       id: 88,
       name: 'Mastic oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/mastic oil.png',
     ),
     Product(
       id: 89,
       name: 'Rice bran oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/rice bran oil.png',
     ),
     Product(
       id: 90,
       name: 'Shea Butter Oil 30ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/shea-butter-oil.png',
     ),
     Product(
       id: 91,
       name: 'Hibiscus oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/hibiscus oil.png',
     ),
     Product(
       id: 92,
       name: 'vanilla oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/vanilla oil.png',
     ),
     Product(
       id: 93,
       name: 'lavender oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/lavandar oil.png',
     ),
     Product(
       id: 94,
       name: 'Henna oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/henna oil.png',
     ),
     Product(
       id: 95,
       name: 'Lettuce oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/luttece-oil.png',
     ),
     Product(
       id: 96,
       name: 'Blue Chamomile Oil 30ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/blue chamomile oil.png',
     ),
     Product(
       id: 97,
       name: 'Harmal oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/harmal oil.png',
     ),
     Product(
       id: 98,
       name: 'Nankha oil 30 ml',
       price: 15.00,
       discountPrice: 9.00,
       imageUrl: 'assets/ajwain oil.png',
     ),
   ],

//Facial scrubs

   [
     Product(
       id: 99,
       name: 'Moisturizing face wash with olive extract',
       price: 50.00,
       discountPrice: 18.00,
       imageUrl: 'assets/facewash olive.png',
     ),
     Product(
       id: 100,
       name: 'Face wash with neem extract for acne',
       price: 50.00,
       discountPrice: 18.00,
       imageUrl: 'assets/facewash nim.png',
     ),
     Product(
       id: 101,
       name: 'Oil control face wash with lemon extract',
       price: 50.00,
       discountPrice: 18.00,
       imageUrl: 'assets/facewash lemon.png',
     ),
     Product(
       id: 102,
       name: 'Deep Cleansing Clay Face Wash',
       price: 50.00,
       discountPrice: 18.00,
       imageUrl: 'assets/facewash mud.png',
     ),
     Product(
       id: 103,
       name: 'Facial wash with aloe vera extract for active skin',
       price: 50.00,
       discountPrice: 18.00,
       imageUrl: 'assets/facewash cactus.png',
     ),
     Product(
       id: 104,
       name: 'Facial wash with cucumber extract to whiten the face',
       price: 50.00,
       discountPrice: 18.00,
       imageUrl: 'assets/facewash cucumber.png',
     ),
     Product(
       id: 105,
       name: 'Facial wash with milk and honey extracts to cleanse the skin',
       price: 50.00,
       discountPrice: 18.00,
       imageUrl: 'assets/facewash milk honey.png',
     ),
     Product(
       id: 106,
       name: 'Nigella sativa face wash herbal extract',
       price: 50.00,
       discountPrice: 22.00,
       imageUrl: 'assets/facewash blackseed.png',
     ),
     Product(
       id: 107,
       name: 'Advanced Black Seed Facial Wash',
       price: 50.00,
       discountPrice: 18.00,
       imageUrl: 'assets/facewash pro.png',
     ),
   ],

// Facial scrubs

   [
     Product(
       id: 108,
       name: 'Facial scrub with apricot and walnut extracts',
       price: 50.00,
       discountPrice: 20.00,
       imageUrl: 'assets/facescrub appricot.png',
     ),
     Product(
       id: 109,
       name: 'Facial scrub with almond extract',
       price: 50.00,
       discountPrice: 25.00,
       imageUrl: 'assets/facescrub almond.png',
     ),
     Product(
       id: 110,
       name: 'Smooth Fruit Facial Scrub',
       price: 50.00,
       discountPrice: 20.00,
       imageUrl: 'assets/facescrub smooth fruit.png',
     ),
     Product(
       id: 111,
       name: 'Facial scrub with pomegranate and aloe vera extracts',
       price: 40.00,
       discountPrice: 20.00,
       imageUrl: 'assets/facescrub cactus.png',
     ),
     Product(
       id: 112,
       name: 'Facial scrub with herbal extracts 5 in 1',
       price: 40.00,
       discountPrice: 20.00,
       imageUrl: 'assets/facescrub herbs.png',
     ),
     Product(
       id: 113,
       name: 'Black Seed Facial Scrub',
       price: 50.00,
       discountPrice: 25.00,
       imageUrl: 'assets/facescrub blackseed.png',
     ),
     Product(
       id: 114,
       name: 'Argan Facial Scrub',
       price: 50.00,
       discountPrice: 22.00,
       imageUrl: 'assets/facescrub aragan.png',
     ),
     Product(
       id: 115,
       name: 'Macadamia Extract Facial Scrub',
       price: 40.00,
       discountPrice: 22.00,
       imageUrl: 'assets/facescrub macadamia.png',
     ),
   ],

// Incense and oud

   [
     Product(
       id: 116,
       name: 'The fragrant oud of guests of gatherings',
       price: 35.00,
       discountPrice: 25.00,imageUrl: 'assets/almajlis oud.png',
     ),
     Product(
       id: 117,
       name: 'Oud, daughter of the scented moon',
       price: 35.00,
       discountPrice: 25.00,
       imageUrl: 'assets/bint alqamar.png',
     ),
     Product(
       id: 118,
       name: 'Oud, daughter of the scented East',
       price: 35.00,
       discountPrice: 25.00,
       imageUrl: 'assets/bint alsharq.png',
     ),
     Product(
       id: 119,
       name: 'Oud Al Wajaha Perfumed',
       price: 35.00,
       discountPrice: 25.00,
       imageUrl: 'assets/alwajahaa oud.png',
     ),
     Product(
       id: 120,
       name: 'Oud al-Maytham scented',
       price: 35.00,
       discountPrice: 25.00,
       imageUrl: 'assets/almatheem oud.png',
     ),
     Product(
       id: 121,
       name: 'Oud Al-Fawah perfume',
       price: 35.00,
       discountPrice: 25.00,
       imageUrl: 'assets/alfawwah oud.png',
     ),
     Product(
       id: 122,
       name: 'Oud Al-Asila perfume',
       price: 35.00,
       discountPrice: 25.00,
       imageUrl: 'assets/alaseela oud.png',
     ),
     Product(
       id: 123,
       name: 'The scented oud of splendor',
       price: 35.00,
       discountPrice: 25.00,
       imageUrl: 'assets/alabbaha oud.png',
     ),
     Product(
       id: 124,
       name: 'Oud, welcome and easy, perfumed',
       price: 35.00,
       discountPrice: 25.00,
       imageUrl: 'assets/ahlan oud.png',
     ),
     Product(
       id: 125,
       name: 'Oud, Princess of the Orient',
       price: 35.00,
       discountPrice: 25.00,
       imageUrl: 'assets/amirat alsharq.png',
     ),
     Product(
       id: 126,
       name: 'Dakhoon Hanadi',
       price: 18.00,
       discountPrice: 12.00,
       imageUrl: 'assets/hanadi bakhoor.png',
     ),
     Product(
       id: 127,
       name: 'Dakhoon Hala',
       price: 18.00,
       discountPrice: 12.00,
       imageUrl: 'assets/hala bakhoor.png',
     ),
     Product(
       id: 128,
       name: 'Dukhun is the Dane of the World',
       price: 18.00,
       discountPrice: 12.00,
       imageUrl: 'assets/dana bakhoor.png',
     ),
     Product(
       id: 129,
       name: 'Dakhoon Hanadi',
       price: 18.00,
       discountPrice: 12.00,
       imageUrl: 'assets/hanadi bakhoor.png',
     ),
     Product(
       id: 130,
       name: 'Dakhoon Tamim',
       price: 18.00,
       discountPrice: 12.00,
       imageUrl: 'assets/tameem bakhoor.png',
     ),
     Product(
       id: 131,
       name: 'Dakhoon Al-Muluk',
       price: 18.00,
       discountPrice: 12.00,
       imageUrl: 'assets/kings bakhoor.png',
     ),
     Product(
       id: 132,
       name: 'Dakhoon Al-Emarat',
       price: 18.00,
       discountPrice: 12.00,
       imageUrl: 'assets/emirates bakhoor.png',
     ),
     Product(
       id: 133,
       name: 'Dokhoon Areej',
       price: 18.00,
       discountPrice: 12.00,
       imageUrl: 'assets/areej bakhoor.png',
     ),
   ],

   [
     Product(
       id: 134,
       name: 'Jeff Soap Clay Mask',
       price: 12.00,
       discountPrice: 8.00,
       imageUrl: 'assets/mud soap.png',
     ),
     Product(
       id: 135,
       name: 'Jif Face Lifting Soap',
       price: 12.00,
       discountPrice: 8.00,
       imageUrl: 'assets/face soap.png',
     ),
     Product(
       id: 136,
       name: 'Jeff Acne Soap',
       price: 12.00,
       discountPrice: 8.00,
       imageUrl: 'assets/young soap.png',
     ),
     Product(
       id: 137,
       name: 'Jif Deodorant Soap with Pomegranate',
       price: 12.00,
       discountPrice: 8.00,
       imageUrl: 'assets/pome soap.png',
     ),
     Product(
       id: 138,
       name: 'Jeff Cucumber Soap',
       price: 12.00,
       discountPrice: 8.00,
       imageUrl: 'assets/cucu soap.png',
     ),
     Product(
       id: 139,
       name: 'Jeff Soap Live',
       price: 12.00,
       discountPrice: 8.00,
       imageUrl: 'assets/snake soap.png',
     ),
     Product(
       id: 140,
       name: 'Jif Milk and Honey Soap',
       price: 12.00,
       discountPrice: 8.00,
       imageUrl: 'assets/milk and honey soap.png',
     ),
     Product(
       id: 141,
       name: 'Jeff Soap Pond',
       price: 12.00,
       discountPrice: 8.00,
       imageUrl: 'assets/elbaraka soap.png',
     ),
     Product(
       id: 142,
       name: 'Jeff Papaya Soap',
       price: 12.00,
       discountPrice: 8.00,
       imageUrl: 'assets/babaya soap.png',
     ),
     Product(
       id: 143,
       name: 'Jif Stretch Mark Removal Soap',
       price: 12.00,
       discountPrice: 8.00,
       imageUrl: 'assets/stress soap.png',
     ),
     Product(
       id: 144,
       name: 'lavender soap',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/lavender soap.png',
     ),
     Product(
       id: 145,
       name: 'turmeric soap',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/kurkum soap.png',
     ),
     Product(
       id: 146,
       name: 'sulfur soap',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/sulfur soap.png',
     ),
     Product(
       id: 147,
       name: 'Glycerin soap – Calthus and tea tree soap',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/calt soap.png',
     ),
     Product(
       id: 148,
       name: 'Honey and glycerine soap',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/honey soap.png',
     ),
     Product(
       id: 149,
       name: 'saffron soap',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/saffron soap.png',
     ),
     Product(
       id: 150,
       name: 'Honey and glycerine soap',
       price: 12.00,
       discountPrice: 7.00,
       imageUrl: 'assets/honey soap.png',
     ),
     Product(
       id: 151,
       name: 'Cucumber and aloe vera soap',
       price: 22.00,
       discountPrice: 14.00,
       imageUrl: 'assets/cucu and cactus soap.png',
     ),
     Product(
       id: 152,
       name: 'Papaya soap with milk',
       price: 22.00,
       discountPrice: 14.00,
       imageUrl: 'assets/babaya and soap.png',
     ),
     Product(
       id: 153,
       name: 'argan soap',
       price: 22.00,
       discountPrice: 14.00,
       imageUrl: 'assets/aragan soap.png',
     ),
   ],
   [
     Product(
       id: 154,
       name: '2 in 1 shampoo and conditioner',
       price: 22.00,
       discountPrice: 16.00,
       imageUrl: 'assets/2 in 1 shampoo.png',
     ),
     Product(
       id: 155,
       name: '2 in 1 shampoo and conditioner (anti-dandruff full of vitamin)',
       price: 22.00,
       discountPrice: 16.00,
       imageUrl: 'assets/anti-dandruff 2 in 1.png',
     ),
     Product(
       id: 156,
       name: '2-in-1 shampoo and conditioner (volume and strength with keratin)',
       price: 22.00,
       discountPrice: 16.00,
       imageUrl: 'assets/stress shampoo 2 in 1.png',
     ),
     Product(
       id: 157,
       name: '2-in-1 shampoo and conditioner (natural nourishment from roots to ends)',
       price: 22.00,
       discountPrice: 16.00,
       imageUrl: 'assets/natural feed 2 in 1 shampoo.png',
     ),
     Product(
       id: 158,
       name: '2-in-1 shampoo and conditioner for smooth and silky hair with Moroccan argan oil extract',
       price: 22.00,
       discountPrice: 16.00,
       imageUrl: 'assets/smooth shampoo.png',
     ),
     Product(
       id: 159,
       name: 'Anti-hair loss shampoo for hijab',
       price: 22.00,
       discountPrice: 16.00,
       imageUrl: 'assets/hijab shampoo.png',
     ),
   ],
];